//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyNhanSuEntities : DbContext
    {
        public QuanLyNhanSuEntities()
            : base("name=QuanLyNhanSuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_BangCong> tb_BangCong { get; set; }
        public virtual DbSet<tb_BaoHiem> tb_BaoHiem { get; set; }
        public virtual DbSet<tb_BoPhan> tb_BoPhan { get; set; }
        public virtual DbSet<tb_ChucVu> tb_ChucVu { get; set; }
        public virtual DbSet<tb_DanToc> tb_DanToc { get; set; }
        public virtual DbSet<tb_LoaiCa> tb_LoaiCa { get; set; }
        public virtual DbSet<tb_LoaiCong> tb_LoaiCong { get; set; }
        public virtual DbSet<tb_NhanVien> tb_NhanVien { get; set; }
        public virtual DbSet<tb_NhanVien_PhuCap> tb_NhanVien_PhuCap { get; set; }
        public virtual DbSet<tb_PhongBan> tb_PhongBan { get; set; }
        public virtual DbSet<tb_PhuCap> tb_PhuCap { get; set; }
        public virtual DbSet<tb_TangCa> tb_TangCa { get; set; }
        public virtual DbSet<tb_TonGiao> tb_TonGiao { get; set; }
        public virtual DbSet<tb_TrinhDo> tb_TrinhDo { get; set; }
        public virtual DbSet<tb_UngLuong> tb_UngLuong { get; set; }
        public virtual DbSet<tb_CongTy> tb_CongTy { get; set; }
        public virtual DbSet<tb_HopDong> tb_HopDong { get; set; }
        public virtual DbSet<tb_KhenThuong_KyLuat> tb_KhenThuong_KyLuat { get; set; }
        public virtual DbSet<tb_DieuChuyen> tb_DieuChuyen { get; set; }
        public virtual DbSet<tb_ThoiViec> tb_ThoiViec { get; set; }
        public virtual DbSet<tb_NangLuong> tb_NangLuong { get; set; }
        public virtual DbSet<tb_KYCONGCHITIET> tb_KYCONGCHITIET { get; set; }
        public virtual DbSet<tb_KyCong> tb_KyCong { get; set; }
        public virtual DbSet<tb_BANGCONG_NHANVIEN_CHITIET> tb_BANGCONG_NHANVIEN_CHITIET { get; set; }
        public virtual DbSet<tb_BoDoi> tb_BoDoi { get; set; }
        public virtual DbSet<tb_Dang_Doan> tb_Dang_Doan { get; set; }
        public virtual DbSet<tb_DienThoaiLienHe> tb_DienThoaiLienHe { get; set; }
        public virtual DbSet<tb_NVDiNuocNgoai> tb_NVDiNuocNgoai { get; set; }
        public virtual DbSet<tb_QueQuan> tb_QueQuan { get; set; }
        public virtual DbSet<tb_QuocTich> tb_QuocTich { get; set; }
        public virtual DbSet<tb_TamTru> tb_TamTru { get; set; }
        public virtual DbSet<tb_ThongTinChinhTri> tb_ThongTinChinhTri { get; set; }
        public virtual DbSet<tb_ThongTinNgoaiNgu> tb_ThongTinNgoaiNgu { get; set; }
        public virtual DbSet<tb_ThongTinNhanVien> tb_ThongTinNhanVien { get; set; }
        public virtual DbSet<tb_ThongTinTrinhDo> tb_ThongTinTrinhDo { get; set; }
        public virtual DbSet<tb_ThongTinViTinh> tb_ThongTinViTinh { get; set; }
        public virtual DbSet<tb_ThuongTru> tb_ThuongTru { get; set; }
        public virtual DbSet<tb_NguoiGTVaoDang> tb_NguoiGTVaoDang { get; set; }
        public virtual DbSet<tb_QuaTrinhDaoTaoCu> tb_QuaTrinhDaoTaoCu { get; set; }
        public virtual DbSet<tb_QuaTrinhDaoTaoMoi> tb_QuaTrinhDaoTaoMoi { get; set; }
        public virtual DbSet<tb_ChiTietKhenThuong> tb_ChiTietKhenThuong { get; set; }
        public virtual DbSet<tb_ChiTietKyLuat> tb_ChiTietKyLuat { get; set; }
        public virtual DbSet<tb_ChiTietHoSoLienQuan> tb_ChiTietHoSoLienQuan { get; set; }
        public virtual DbSet<tb_HoSoTuyenDung> tb_HoSoTuyenDung { get; set; }
        public virtual DbSet<tb_ThongTinGiaDinh> tb_ThongTinGiaDinh { get; set; }
        public virtual DbSet<tb_QuaTrinhLamViecCuaThanNhan> tb_QuaTrinhLamViecCuaThanNhan { get; set; }
        public virtual DbSet<tb_LichSuBanThanNhanVien> tb_LichSuBanThanNhanVien { get; set; }
        public virtual DbSet<tb_ThongTinHopDongLaoDong> tb_ThongTinHopDongLaoDong { get; set; }
        public virtual DbSet<tb_QuaTrinhCongTac> tb_QuaTrinhCongTac { get; set; }
    }
}
