//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ChiTietKhenThuong
    {
        public int Id { get; set; }
        public Nullable<int> MaNV { get; set; }
        public string HinhThuc { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public string LyDo { get; set; }
        public string CapQuyetDinh { get; set; }
        public string SoQuyetDinh { get; set; }
        public string NguoiKy { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public string GhiChu { get; set; }
        public string DinhKem { get; set; }
        public string HoTen { get; set; }
    
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
