//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DienThoaiLienHe
    {
        public int Id { get; set; }
        public Nullable<int> MaNV { get; set; }
        public string DienThoaiNha { get; set; }
        public string DTDD { get; set; }
        public string Email { get; set; }
    
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
