//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Dang_Doan
    {
        public int Id { get; set; }
        public Nullable<int> MaNV { get; set; }
        public string SoTheDoan { get; set; }
        public Nullable<System.DateTime> NgayCapThe { get; set; }
        public Nullable<bool> DaVaoDoan { get; set; }
        public Nullable<System.DateTime> NgayVaoDangLan1 { get; set; }
        public Nullable<System.DateTime> NgayChinhThucLan1 { get; set; }
        public Nullable<System.DateTime> NgayVaoDangLan2 { get; set; }
        public Nullable<System.DateTime> NgayChinhThucLan2 { get; set; }
        public Nullable<System.DateTime> NgayVaoDoan { get; set; }
        public Nullable<bool> DaVaoDang { get; set; }
    
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
