//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_QuaTrinhDaoTaoMoi
    {
        public int Id { get; set; }
        public Nullable<int> MaNV { get; set; }
        public string HoTen { get; set; }
        public string KhoaHoc { get; set; }
        public string Truong_DonVi { get; set; }
        public Nullable<bool> HoanTat { get; set; }
        public string Bang { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string SoQuyetDinh { get; set; }
        public string HinhThuc { get; set; }
        public string TenBang { get; set; }
        public string SoBang { get; set; }
        public string DangBang { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public Nullable<bool> HetHan { get; set; }
        public string KetQua { get; set; }
        public string DiaDiem { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
