//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_QuaTrinhCongTac
    {
        public int Id { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public string TenCongTy { get; set; }
        public string TenPhongBan { get; set; }
        public string TenDoi { get; set; }
        public string ChucDanh { get; set; }
        public string LyDo { get; set; }
        public Nullable<bool> DangHoatDong { get; set; }
        public string SoHDLD { get; set; }
        public string LoaiHDLD { get; set; }
        public Nullable<System.DateTime> NgayQuyetDinh { get; set; }
        public Nullable<System.DateTime> NgayHieuLuc { get; set; }
        public string SoQD { get; set; }
        public string NguoiKy { get; set; }
        public string FileQuyetDinh { get; set; }
        public Nullable<int> Loai { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
