//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ThongTinGiaDinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ThongTinGiaDinh()
        {
            this.tb_QuaTrinhLamViecCuaThanNhan = new HashSet<tb_QuaTrinhLamViecCuaThanNhan>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MaNV { get; set; }
        public string HoTen { get; set; }
        public string QuanHe { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string Phuong { get; set; }
        public string QuanHuyen { get; set; }
        public string TinhThanh { get; set; }
        public Nullable<bool> ConSong { get; set; }
    
        public virtual tb_NhanVien tb_NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_QuaTrinhLamViecCuaThanNhan> tb_QuaTrinhLamViecCuaThanNhan { get; set; }
    }
}
