//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ThongTinTrinhDo
    {
        public int Id { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<System.DateTime> TuNam { get; set; }
        public Nullable<System.DateTime> DenNam { get; set; }
        public string CheDoHoc { get; set; }
        public string LoaiDaoTao { get; set; }
        public string TruongDaoTao { get; set; }
        public string NganhDaoTao { get; set; }
        public string BangCap { get; set; }
        public string NoiDung { get; set; }
        public string KetQua { get; set; }
        public string ThoiGian { get; set; }
        public string ChuyenMon { get; set; }
        public string SoBang { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string QuocGia { get; set; }
    
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
