//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ThongTinNhanVien
    {
        public int Id { get; set; }
        public string HoKhaiSinh { get; set; }
        public string HoThuongDung { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string TheCanCuoc { get; set; }
        public string SoHoChieu { get; set; }
        public string TenKhaiSinh { get; set; }
        public string TenThuongDUng { get; set; }
        public string BiDanh { get; set; }
        public string CMND { get; set; }
        public string NoiCapCMND { get; set; }
        public Nullable<System.DateTime> NgayCapTheCC { get; set; }
        public Nullable<System.DateTime> NgayCapHoChie { get; set; }
    
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
