//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ThongTinHopDongLaoDong
    {
        public int Id { get; set; }
        public Nullable<int> MaNV { get; set; }
        public string SoHDLD { get; set; }
        public string LoaiHopDong { get; set; }
        public string ThoiHan { get; set; }
        public string ChucDanh { get; set; }
        public Nullable<double> BacLuong { get; set; }
        public Nullable<double> HeSoLuong { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public string NguoiKy { get; set; }
        public Nullable<System.DateTime> NgayThuViec { get; set; }
        public Nullable<System.DateTime> NgayChinhThuc { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public Nullable<System.DateTime> NgayGiaHan { get; set; }
        public string FileQuyetDinh { get; set; }
        public string FileHDLD { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
