//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UngLuong
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Nam { get; set; }
        public Nullable<System.DateTime> Thang { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<double> SoTien { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> MaNV { get; set; }
    
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
